exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user start hyprpolkitagent
exec-once = awww-daemon
exec-once = hypridle
exec-once = env QT_QUICK_CONTROLS_STYLE=Basic quickshell -p ~/.config/arch-shell
exec-once = ~/.config/hypr/scripts/init-wallpaper.sh
exec-once = playerctld
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
