layerrule {
    name = "hyprpicker-no-anim"
    match:namespace = hyprpicker
    no_anim = on
}

layerrule {
    name = "session-lock-blur"
    match:namespace = ext-session-lock
    blur = on
    ignore_alpha = 0.2
}
