font_family      JetBrainsMono Nerd Font
font_size        11.0
bold_font        auto
italic_font      auto
bold_italic_font auto

cursor_trail 1
background_opacity 0.7
confirm_os_window_close 0
scrollback_lines 2000
wheel_scroll_min_lines 1
enable_audio_bell no
hide_window_decorations yes
window_padding_width 4

foreground #e6edf3
background #1a1f28
selection_foreground #1a1f28
selection_background #0078d4
cursor #0078d4
url_color #60cdff
color0 #1a1f28
color8 #5b6573
color1 #f85149
color9 #ff7b72
color2 #3fb950
color10 #56d364
color3 #d29922
color11 #e3b341
color4 #0078d4
color12 #58a6ff
color5 #bc8cff
color13 #d2a8ff
color6 #39c5cf
color14 #56d4dd
color7 #e6edf3
color15 #ffffff
